name: sangeet
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"
dependencies:
  app_links: 2.2.2
  audio_service: ^0.18.9
  audio_session: any
  audiotagger: ^2.2.1
  avatar_glow: ^3.0.1
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^10.1.2
  file_picker: ^8.1.2
  firebase_core: ^3.4.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_displaymode: ^0.6.0
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  flutter_lyric: ^2.0.4+6
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  just_audio: ^0.9.32
  # Discontinued, Use just_audio_windows instead.
  # just_audio_libwinmedia: ^0.0.4 # For windows and linux.
  logging: ^1.1.1
  marquee: ^2.2.3
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.6.1
  package_info_plus: ^8.0.2
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.12
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.4.5
  rxdart: any
  salomon_bottom_bar: ^3.3.1
  share_plus: ^10.0.2
  sliding_up_panel: ^2.0.0+1
  speech_to_text: ^7.0.0
  url_launcher: ^6.1.8
  uuid: ^4.5.0
  youtube_explode_dart: ^2.2.1

dependency_overrides:
  fading_edge_scrollview:
    git:
      url: https://github.com/Envoy-Z-Dev/fading_edge_scrollview

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  msix: ^3.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

msix_config:
  display_name: Sangeet
  publisher_display_name: Suman Dey
  identity_name: com.suman.sangeet
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
